feat: fake-admin-panel
Aju100/Django-Backend-mentorship pull request #49
Opened 2021-05-27 10:27 UTC by Romansth

Hi @Aju100  I've made the following changes in the project repo:
1. Added Roman and Nirajan's names on CONTRIBUTERS.txt
2. Added admin_honeypot in the list installed apps in settings.py
3. Created a new url route to 'admin/' for fake admin page while the real admin page login route has been set to 'admin-auth/' .
4. Added honeypot package to local.txt and base.txt.
The changes have no conflict with the current version of the repo and the fake admin route is also working properly.
![honey](https://user-images.githubusercontent.com/53575561/119810863-2e27c780-bf06-11eb-8890-28af701e18ce.jpg)

2021-05-27 12:21 UTC, Aju100 requested changes
Remove the CONTRIBUTORS.txt as this was assigned for nirajan

2021-05-27 12:59 UTC, Romansth commented
@Aju100  I have undo the CONTRIBUTORS.txt file edit.

2021-05-27 13:11 UTC, Aju100 requested changes
You need to remove the whole file CONTRIBUTORS.txt and also make the URL path update in urls.py .
```    
path('shaiho/', admin.site.urls),
```

2021-05-28 01:16 UTC, Aju100 approved these changes

2021-05-28 01:17 UTC, merged